### ISSUE TITLE
Fan speed doesn't work (fan with 26 speeds)

### ISSUE THREAD

**Issue by c-david-j** [0x5e/homebridge-tuya-platform#44]
**Describe the bug**
The fan speed slider does not change the speed of the fan. After changing the fan speed, it just jumps back to the speed it was originally set at. It has no affect on the fan. 

The fan has 26 speeds. HomeKit seems to think the fan speed is a percentage, i.e. when the fan is manually set to 13, HomeKit reads this as 13%, NOT 50%.

_(As well as this, there's no function to allow oscillation or change between normal/natural/sleep modes but I don't think they're as important!)_

**Expected behavior**
Expect the slider to change the fan speed. When the fan is set to one of its speed settings, HomeKit should convert that to a percentage and reflect that in the app.

**Device info**
Duux Whisper Flex fan

[11/4/2022, 3:54:55 PM] [TuyaPlatform] [TuyaOpenAPI] response:
path = /v1.0/homes/67295685/devices
data = {
  "result": [
    {
      "active_time": 1667573694,
      "biz_type": 18,
      "category": "fs",
      "create_time": 1658275815,
      "icon": "smart/icon/ay1536760473930cDk1Q/d70c5f0496414545f70634d132c6344d.jpg",
      "id": "xxxxxx",
      "ip": "xxxxxx",
      "lat": "xxxxxx",
      "local_key": "xxxxxx",
      "lon": "xxxxxx",
      "model": "DXCF10/11/12/13",
      "name": "Small Fan",
      "online": true,
      "owner_id": "xxxxxx",
      "product_id": "dune79w7bsu6dg3e",
      "product_name": "Whisper Flex",
      "status": [
        {
          "code": "switch",
          "value": false
        },
        {
          "code": "mode",
          "value": "sleep"
        },
        {
          "code": "fan_speed",
          "value": "3"
        },
        {
          "code": "switch_horizontal",
          "value": "false"
        },
        {
          "code": "switch_vertical",
          "value": "false"
        },
        {
          "code": "countdown",
          "value": "0"
        },
        {
          "code": "countdown_left",
          "value": 0
        }
      ],
      "sub": false,
      "time_zone": "+00:00",
      "uid": "eu1664746892538eLmFk",
      "update_time": 1667573696,
      "uuid": "d632a217a3918459"
    }
  ],
  "success": true,
  "t": 1667577295074,
  "tid": "068c3ea95c5911ed8bef9ee482573564"
}
[11/4/2022, 3:54:55 PM] [TuyaPlatform] [TuyaOpenAPI] request:
method = get
endpoint = https://openapi.tuyaeu.com
path = /v1.0/devices/bf62f927840f8abc42atws/specifications
query = undefined
headers = {
  "t": "xxxxxx",
  "client_id": "xxxxxx",
  "nonce": "40809ba0-c4f7-4155-9733-572799b065b3",
  "Signature-Headers": "client_id",
  "sign": "xxxxxx",
  "sign_method": "HMAC-SHA256",
  "access_token": "xxxxxx",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.6.0-beta.23"
}
body = null
[11/4/2022, 3:54:55 PM] [TuyaPlatform] [TuyaOpenMQ] connected
[11/4/2022, 3:54:55 PM] [TuyaPlatform] [TuyaOpenAPI] response:
path = /v1.0/devices/xxxxxx/specifications
data = {
  "result": {
    "category": "fs",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\"]}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"nature\",\"sleep\",\"smart\"]}"
      },
      {
        "code": "switch_horizontal",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_vertical",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\"]}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"nature\",\"sleep\",\"smart\"]}"
      },
      {
        "code": "switch_horizontal",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_vertical",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\"]}"
      },
      {
        "code": "countdown_left",
        "type": "Integer",
        "values": "{\"unit\":\"h\",\"min\":0,\"max\":12,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1667577295265,
  "tid": "xxxxxx"
}
[11/4/2022, 3:54:55 PM] [TuyaPlatform] Got 1 device(s).
[11/4/2022, 3:54:55 PM] [TuyaPlatform] Device list saved at /Users/chrisjohnson/.homebridge/persist/TuyaDeviceList.eu1664746892538eLmFk.json
[11/4/2022, 3:54:55 PM] [TuyaPlatform] Restoring existing accessory from cache: Small Fan
[11/4/2022, 3:54:55 PM] [TuyaPlatform] Set props for RotationSpeed: {"minValue":0,"maxValue":100,"minStep":1}

INCREASING SPEED OF FAN (FAILS)

[11/4/2022, 4:01:51 PM] [TuyaPlatform] [TuyaOpenAPI] request:
method = post
endpoint = https://openapi.tuyaeu.com
path = /v1.0/devices/bf62f927840f8abc42atws/commands
query = null
headers = {
  "t": "xxxxx",
  "client_id": "xxxxx",
  "nonce": "xxxxx",
  "Signature-Headers": "client_id",
  "sign": "xxxxx",
  "sign_method": "HMAC-SHA256",
  "access_token": "xxxxx",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.6.0-beta.23"
}
body = {
  "commands": [
    {
      "code": "fan_speed",
      "value": 19
    }
  ]
}
[11/4/2022, 4:01:52 PM] [TuyaPlatform] [TuyaOpenAPI] response:
path = /v1.0/devices/bf62f927840f8abc42atws/commands
data = {
  "code": 1104,
  "msg": "type is incorrect",
  "success": false,
  "t": 1667577712050,
  "tid": "ff13aa855c5911ed8a2efe1b67a66e75"

**Comment by 0x5e** [comment]
Thanks for the feedback. Please upload `~/.homebridge/persist/TuyaDeviceList.eu1664746892538eLmFk.json` too.
Currently I have no idea how to support mode change for devices will be better. Because most of the mode is emum type, which means If I use switch, 5 enum will need 5 switches, and each switch have on and off, that confuse people. And extra code to keep 5 switch in relationship, when one turns on, others has to be turned off.

**Comment by c-david-j** [comment]
Yes, understood! Would just be great to have the fan speed working.

TuyaDeviceList file attached - thanks!

[TuyaDeviceList.eu1664746892538eLmFk.json.zip](https://github.com/0x5e/homebridge-tuya-platform/files/9940350/TuyaDeviceList.eu1664746892538eLmFk.json.zip)

**Comment by 0x5e** [comment]
Should fixed. Please try the latest version.

**Comment by c-david-j** [comment]
Hi, sadly this didn't work. The slider now goes up and down, but the fan speed doesn't change.

[11/6/2022, 9:00:11 AM] [TuyaPlatform] [TuyaOpenAPI] response:
path = /v1.0/homes/67295685/devices
data = {
  "result": [
    {
      "active_time": 1667724517,
      "biz_type": 18,
      "category": "fs",
      "create_time": 1658275815,
      "icon": "smart/icon/ay1536760473930cDk1Q/d70c5f0496414545f70634d132c6344d.jpg",
      "id": "xxxx",
      "ip": "xxxx",
      "lat": "xxxx",
      "local_key": "xxxx",
      "lon": "xxxx",
      "model": "DXCF10/11/12/13",
      "name": "Small Fan",
      "online": true,
      "owner_id": "67295685",
      "product_id": "dune79w7bsu6dg3e",
      "product_name": "Whisper Flex",
      "status": [
        {
          "code": "switch",
          "value": true
        },
        {
          "code": "mode",
          "value": "sleep"
        },
        {
          "code": "fan_speed",
          "value": "15"
        },
        {
          "code": "switch_horizontal",
          "value": "false"
        },
        {
          "code": "switch_vertical",
          "value": "false"
        },
        {
          "code": "countdown",
          "value": "0"
        },
        {
          "code": "countdown_left",
          "value": 0
        }
      ],
      "sub": false,
      "time_zone": "+00:00",
      "uid": "eu1664746892538eLmFk",
      "update_time": 1667724518,
      "uuid": "d632a217a3918459"
    }
  ],
  "success": true,
  "t": 1667725211798,
  "tid": "6bca997b5db111ed8bfc9ee482573564"
}
[11/6/2022, 9:00:11 AM] [TuyaPlatform] [TuyaOpenAPI] request:
method = get
endpoint = https://openapi.tuyaeu.com
path = /v1.0/devices/bf62f927840f8abc42atws/specifications
query = undefined
headers = {
  "t": "1667725211792",
  "client_id": "xxxxx",
  "nonce": "xxxxx",
  "Signature-Headers": "client_id",
  "sign": "xxxxx",
  "sign_method": "HMAC-SHA256",
  "access_token": "xxxxx",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.6.0-beta.25"
}
body = null
[11/6/2022, 9:00:11 AM] [TuyaPlatform] [TuyaOpenMQ] connected
[11/6/2022, 9:00:11 AM] [TuyaPlatform] [TuyaOpenAPI] response:
path = /v1.0/devices/bf62f927840f8abc42atws/specifications
data = {
  "result": {
    "category": "fs",
    "functions": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\"]}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"nature\",\"sleep\",\"smart\"]}"
      },
      {
        "code": "switch_horizontal",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_vertical",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\"]}"
      }
    ],
    "status": [
      {
        "code": "switch",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "fan_speed",
        "type": "Enum",
        "values": "{\"range\":[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\"]}"
      },
      {
        "code": "mode",
        "type": "Enum",
        "values": "{\"range\":[\"nature\",\"sleep\",\"smart\"]}"
      },
      {
        "code": "switch_horizontal",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "switch_vertical",
        "type": "Boolean",
        "values": "{}"
      },
      {
        "code": "countdown",
        "type": "Enum",
        "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\"]}"
      },
      {
        "code": "countdown_left",
        "type": "Integer",
        "values": "{\"unit\":\"h\",\"min\":0,\"max\":12,\"scale\":0,\"step\":1}"
      }
    ]
  },
  "success": true,
  "t": 1667725211994,
  "tid": "6bee43095db111edb42fe68f1605df98"
}
[11/6/2022, 9:00:11 AM] [TuyaPlatform] Got 1 device(s).
[11/6/2022, 9:00:11 AM] [TuyaPlatform] Device list saved at /Users/chrisjohnson/.homebridge/persist/TuyaDeviceList.eu1664746892538eLmFk.json
[11/6/2022, 9:00:11 AM] [TuyaPlatform] Restoring existing accessory from cache: Small Fan


CHANGING FAN SPEED ON HOME APP

[11/6/2022, 9:02:19 AM] [TuyaPlatform] [TuyaOpenAPI] request:
method = post
endpoint = https://openapi.tuyaeu.com
path = /v1.0/devices/bf62f927840f8abc42atws/commands
query = null
headers = {
  "t": "1667725339167",
  "client_id": "fap93kjfn4nxngtw9a55",
  "nonce": "f9ae9a9e-9626-42bd-8791-9fd53e28dfae",
  "Signature-Headers": "client_id",
  "sign": "990B795BCFB7A5FD307FF60E94606D316A7777F4274AF022537484F43EB5AC7E",
  "sign_method": "HMAC-SHA256",
  "access_token": "940bf1a7b03a14cd8a7ddb67caffcec2",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.6.0-beta.25"
}
body = {
  "commands": [
    {
      "code": "switch",
      "value": true
    },
    {
      "code": "fan_speed",
      "value": 55
    }
  ]
}
[11/6/2022, 9:02:19 AM] [TuyaPlatform] [TuyaOpenAPI] response:
path = /v1.0/devices/bf62f927840f8abc42atws/commands
data = {
  "code": 1101,
  "msg": "params range invalid",
  "success": false,
  "t": 1667725339341,
  "tid": "b7d4a67a5db111ed8bfc9ee482573564"
}

**Comment by 0x5e** [comment]
It's weird. the value of your `fan_speed` range is string, but when it is being sent, it was changed into number. I'm not TypeScript and JavaScript expert, let me have a test again.

**Comment by 0x5e** [comment]
Your device's `fan_speed ` is enum, which should be integer by default. Maybe your device is non-stantard. I will submit a new version to compatible yours and please help me have a try. I couldn't find a virtual device same as yours to reproduce the problem.

**Comment by 0x5e** [comment]
Please try beta.26. Hope it fixed now. @c-david-j

**Comment by c-david-j** [comment]
Thanks 0x5e - looks like there's still a problem, it's strange! When changing the fan speed through HomeKit, the Homebridge logs say that the change was made and was successful - but the fan doesn't actually change speed.

I should say, I can live without this working, but I thought you'd like to know so that your plugin can work with as many devices as possible! :)

If the speed of the fan is changed in the Smart Life app, the speed in the Home app changes to show the correct speed (in percentage) - so the issue now just seems to be that the slider doesn't change the fan speed of the actual device. 

**Log for changing the speed to 76% in HomeKit - sends speed 20 to the device, which is correct - but the fan doesn't actually change speed - it just stays at the same speed it already was** 

[11/7/2022, 9:19:37 AM] [TuyaPlatform] Set RotationSpeed to: 20
[11/7/2022, 9:19:37 AM] [TuyaPlatform] [TuyaOpenAPI] request:
method = post
endpoint = https://openapi.tuyaeu.com
path = /v1.0/devices/bf62f927840f8abc42atws/commands
query = null
headers = {
  "t": "1667812777987",
  "client_id": "fap93kjfn4nxngtw9a55",
  "nonce": "e637f14b-4ad9-4659-95e7-1773cee7effd",
  "Signature-Headers": "client_id",
  "sign": "16BFB418AECA7CA9CBD40574D61276FC83AAB654701836CB5A43E568426A3890",
  "sign_method": "HMAC-SHA256",
  "access_token": "96658b88cc068df6c80c1e46ef2b7f3f",
  "lang": "en",
  "dev_lang": "javascript",
  "dev_channel": "homebridge",
  "devVersion": "1.6.0-beta.26"
}
body = {
  "commands": [
    {
      "code": "switch",
      "value": true
    },
    {
      "code": "fan_speed",
      "value": "20"
    }
  ]
}
[11/7/2022, 9:19:38 AM] [TuyaPlatform] [TuyaOpenAPI] response:
path = /v1.0/devices/bf62f927840f8abc42atws/commands
data = {
  "result": true,
  "success": true,
  "t": 1667812778248,
  "tid": "4d7ab5a55e7d11edb43ce68f1605df98"
}


Unfortunately there doesn't seem to be a log when I change the fan speed in Smart Life - but as I said, when you change the speed in Smart Life, HomeKit now correctly adjusts the speed in the Home app, so it's the correct percentage. It just doesn't work the other way round.

**Comment by 0x5e** [comment]
Yes I'd like to work with as many devices as possible, according to your descriptions, and I've asked my ex colleague, I think the reason maybe like this:

There's `standard instruction/status set` and `non-standard instruction/status set`.
The `non-standard instruction/status set` we can't get from Tuya OpenAPI.
Your device's manutactor didn't use the `standard instruction/status set` when developing the products. So we can't support them. 

In @c-david-j 's case, `fan_speed` sounds like a readonly state, not writable (write is not useful), and the real-writable function is non-standard so it's invisible. 
#58 @mitch5772 's case is similar too, it doesn't have any `standard instruction/status set` so we can't control it from Tuya Platform Web Debugging or HomeBridge at all.

The solution may be small hope, but can have a try:
Try to contact your device's manufactor company (not Tuya), let them to submit a request to Tuya, request for expose device's `non-standard instruction/status set`.
The request must be submitted by manufactor company, not customer.

**Comment by 0x5e** [comment]
#111
